# Generated by Django 5.2.8 on 2026-02-15 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_object_id', models.UUIDField()),
                ('image', models.ImageField(upload_to='post_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('post_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_%(app_label)s_%(class)s_related', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPost',
            fields=[
                ('author_object_id', models.UUIDField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('event', 'Event'), ('other', 'Other')], default='service', max_length=50)),
                ('price_range', models.CharField(blank=True, help_text='e.g., $10-$50, negotiable, etc.', max_length=100, null=True)),
                ('delivery_time', models.CharField(blank=True, choices=[('night', 'Night'), ('day', 'Day'), ('7_days', '7 Days'), ('14_days', '14 Days')], max_length=20, null=True)),
                ('author_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_authored_posts', related_query_name='%(app_label)s_%(class)s_authored_post_query', to='contenttypes.contenttype')),
                ('tags', models.ManyToManyField(blank=True, to='posts.tag')),
            ],
            options={
                'verbose_name': 'Offer Post',
                'verbose_name_plural': 'Offer Posts',
            },
        ),
        migrations.CreateModel(
            name='NeedPost',
            fields=[
                ('author_object_id', models.UUIDField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_authored_posts', related_query_name='%(app_label)s_%(class)s_authored_post_query', to='contenttypes.contenttype')),
                ('tags', models.ManyToManyField(blank=True, to='posts.tag')),
            ],
            options={
                'verbose_name': 'Need Post',
                'verbose_name_plural': 'Need Posts',
            },
        ),
    ]
