# Generated by Django 5.2.8 on 2026-03-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_image_post_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='needpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('logistic', 'Logistic'), ('marketing', 'Marketing'), ('legal', 'Legal'), ('suply_chain', 'Suply Chain'), ('finance', 'Finance'), ('design', 'Design'), ('other', 'Other')], default=23, help_text='Required category for the need post', max_length=50),
            preserve_default=False,
        ),
    ]
