# Generated by Django 5.2.8 on 2026-03-29 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0003_needpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedPostProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer_object_id', models.UUIDField()),
                ('message', models.TextField(blank=True, help_text='Optional message or proposal details', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='posts.needpost')),
                ('proposer_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('need_post', 'proposer_content_type', 'proposer_object_id')},
            },
        ),
    ]
