# Generated by Django 5.2.8 on 2026-03-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_needpostproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='needpostproposal',
            name='cv_file',
            field=models.FileField(blank=True, help_text='CV or supporting document (PDF/Image)', null=True, upload_to='proposals/cvs/'),
        ),
        migrations.AlterField(
            model_name='needpostproposal',
            name='message',
            field=models.TextField(blank=True, help_text='Cover letter or proposal message', null=True),
        ),
    ]
