# Generated by Django 5.2.8 on 2026-03-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_needpostproposal_cv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needpostproposal',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject of the proposal', max_length=255, null=True),
        ),
    ]
