# Generated by Django 5.2.8 on 2026-04-01 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_needpostproposal_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needpostproposal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
