# Generated by Django 5.2.8 on 2026-04-08 00:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0007_alter_needpostproposal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPostProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposer_object_id', models.UUIDField()),
                ('subject', models.CharField(blank=True, help_text='Subject of the proposal', max_length=255, null=True)),
                ('message', models.TextField(blank=True, help_text='Message or inquiry about the offer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('offer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='posts.offerpost')),
                ('proposer_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('offer_post', 'proposer_content_type', 'proposer_object_id')},
            },
        ),
    ]
