# Generated by Django 5.2.8 on 2026-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_offerpostproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpostproposal',
            name='attachment',
            field=models.FileField(blank=True, help_text='Any supporting document or requirement brief', null=True, upload_to='proposals/attachments/'),
        ),
        migrations.AddField(
            model_name='offerpostproposal',
            name='budget',
            field=models.CharField(blank=True, help_text='Proposed budget (e.g., $100, negotiable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerpostproposal',
            name='expected_delivery',
            field=models.CharField(blank=True, help_text='Desired timeline or delivery date', max_length=100, null=True),
        ),
    ]
