# Generated by Django 5.2.8 on 2026-04-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_offerpostproposal_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpost',
            name='delivery_time',
            field=models.CharField(blank=True, help_text='e.g., 3-5 days, immediate, etc.', max_length=100, null=True),
        ),
    ]
