# Generated by Django 5.2.8 on 2026-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_offerpost_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('logistic', 'Logistic'), ('marketing', 'Marketing'), ('legal', 'Legal'), ('suply_chain', 'Suply Chain'), ('finance', 'Finance'), ('design', 'Design'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
