# Generated by Django 5.2.8 on 2026-05-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_offerpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needpost',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Logistic', 'Logistic'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Supply Chain', 'Supply Chain'), ('Finance', 'Finance'), ('Design', 'Design'), ('Other', 'Other')], help_text='Required category for the need post', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerpost',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Logistic', 'Logistic'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Supply Chain', 'Supply Chain'), ('Finance', 'Finance'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
