# Generated by Django 5.2.8 on 2025-11-18 19:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text="User's email address (used for login)", max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(help_text="User's full name", max_length=150, verbose_name='full name')),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text="User's gender", max_length=20, null=True, verbose_name='gender')),
                ('occupation', models.CharField(blank=True, help_text="User's occupation", max_length=100, null=True, verbose_name='occupation')),
                ('country', models.CharField(blank=True, help_text="User's country", max_length=100, null=True, verbose_name='country')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='staff status')),
                ('is_email_verified', models.BooleanField(default=False, help_text="Designates whether user's email has been verified", verbose_name='email verified')),
                ('is_subscribed', models.BooleanField(default=False, help_text='Designates whether the user has an active subscription', verbose_name='subscribed')),
                ('firebase_uid', models.CharField(blank=True, db_index=True, help_text='Firebase UID for social login integration', max_length=128, null=True, unique=True, verbose_name='firebase uid')),
                ('auth_provider', models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('apple', 'Apple')], default='email', help_text='Primary authentication method used by user', max_length=50, verbose_name='authentication provider')),
                ('profile_picture', models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pictures/', verbose_name='profile picture')),
                ('bio', models.TextField(blank=True, help_text="User's bio", null=True, verbose_name='bio')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when user registered', verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, help_text="Date of user's last login", null=True, verbose_name='last login')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time user data was updated', verbose_name='updated at')),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('journal_pin', models.CharField(blank=True, max_length=128, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('pt', 'Portuguese')], default='en', help_text="User's preferred language for API responses", max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='Time of login')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address used for login', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device user agent string', null=True)),
                ('auth_method', models.CharField(default='email', help_text='Authentication method used', max_length=50)),
                ('user', models.ForeignKey(help_text='User who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login history',
                'verbose_name_plural': 'login histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firebase_uid'], name='users_user_firebas_b8ee51_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_email_verified'], name='users_user_is_acti_11f219_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginhistory',
            index=models.Index(fields=['user', '-login_time'], name='users_userl_user_id_b5dceb_idx'),
        ),
    ]
