# Generated by Django 5.2.8 on 2026-01-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_remove_journal_pin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_firebas_b8ee51_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='userloginhistory',
            name='auth_method',
        ),
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='profiledatadeletionrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set_custom', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_permissions_custom', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='user',
            field=models.ForeignKey(help_text='User who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='users.user'),
        ),
    ]
