# Generated by Django 5.2.8 on 2026-01-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_accountdeletionrequest_name_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text="User's cover photo", null=True, upload_to='cover_photos/', verbose_name='cover photo'),
        ),
    ]
