# Generated by Django 5.2.8 on 2026-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cover_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Designates whether the user has completed their profile registration', verbose_name='profile complete'),
        ),
    ]
