# Generated by Django 5.2.8 on 2026-01-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_cover_photo_user_is_profile_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_profile_complete',
        ),
    ]
