# Generated by Django 5.2.8 on 2026-04-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Designates whether the user has completed their profile registration', verbose_name='profile complete'),
        ),
    ]
