# Generated by Django 5.2.8 on 2026-04-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text="User's cover photo", null=True, upload_to='cover_photos/', verbose_name='cover photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, help_text="A short headline or status for the user's profile", max_length=255, null=True, verbose_name='headline'),
        ),
    ]
