# Generated by Django 5.2.8 on 2026-04-16 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_cover_photo_user_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, verbose_name='school')),
                ('degree', models.CharField(max_length=255, verbose_name='degree')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='field of study')),
                ('grade', models.CharField(blank=True, max_length=100, null=True, verbose_name='grade')),
                ('activities_and_societies', models.TextField(blank=True, null=True, verbose_name='activities and societies')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this education belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'educations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('company', models.CharField(max_length=255, verbose_name='company')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('self_employed', 'Self-employed'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('trainee', 'Trainee')], max_length=50, null=True, verbose_name='employment type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this experience belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'experience',
                'verbose_name_plural': 'experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
