# Generated by Django 5.2.8 on 2026-04-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_education_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, help_text="User's about section", null=True, verbose_name='about'),
        ),
    ]
