# Generated by Django 5.2.8 on 2026-04-23 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0012_remove_user_bio_user_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_object_id', models.UUIDField()),
                ('giver_object_id', models.UUIDField()),
                ('message', models.TextField(verbose_name='recommendation message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giver_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_recommendations_ct', to='contenttypes.contenttype')),
                ('receiver_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations_ct', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'recommendation',
                'verbose_name_plural': 'recommendations',
                'ordering': ['-created_at'],
                'unique_together': {('receiver_content_type', 'receiver_object_id', 'giver_content_type', 'giver_object_id')},
            },
        ),
    ]
