# Generated by Django 5.2.8 on 2026-04-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0013_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_object_id', models.UUIDField()),
                ('followed_object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_ct', to='contenttypes.contenttype')),
                ('follower_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_ct', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'follow',
                'verbose_name_plural': 'follows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower_content_type', 'follower_object_id'], name='users_follo_followe_374d65_idx'), models.Index(fields=['followed_content_type', 'followed_object_id'], name='users_follo_followe_0dcd45_idx')],
                'unique_together': {('follower_content_type', 'follower_object_id', 'followed_content_type', 'followed_object_id')},
            },
        ),
    ]
