# Generated by Django 5.2.8 on 2026-08-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0014_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocker_object_id', models.UUIDField()),
                ('blocked_object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_ct', to='contenttypes.contenttype')),
                ('blocker_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_accounts_ct', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'user block',
                'verbose_name_plural': 'user blocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker_content_type', 'blocker_object_id'], name='users_userb_blocker_19d544_idx'), models.Index(fields=['blocked_content_type', 'blocked_object_id'], name='users_userb_blocked_bce2e4_idx')],
                'unique_together': {('blocker_content_type', 'blocker_object_id', 'blocked_content_type', 'blocked_object_id')},
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_object_id', models.UUIDField()),
                ('target_object_id', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('harassment', 'Harassment or bullying'), ('inappropriate', 'Inappropriate content'), ('fake_account', 'Fake account or impersonation'), ('scam', 'Fraud or scam'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted_ct', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received_ct', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'user report',
                'verbose_name_plural': 'user reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter_content_type', 'reporter_object_id'], name='users_userr_reporte_2f42b3_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='users_userr_target__60177b_idx'), models.Index(fields=['status'], name='users_userr_status_2b8656_idx')],
            },
        ),
    ]
