# Generated by Django 5.2.8 on 2026-04-07 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part1_object_id', models.UUIDField()),
                ('part2_object_id', models.UUIDField()),
                ('post_object_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Message Request'), ('active', 'Active Chat'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part1_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_part1', to='contenttypes.contenttype')),
                ('part2_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_part2', to='contenttypes.contenttype')),
                ('post_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('part1_content_type', 'part1_object_id', 'part2_content_type', 'part2_object_id', 'post_content_type', 'post_object_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_object_id', models.UUIDField()),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
