# Generated by Django 5.2.8 on 2026-01-28 21:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the business account', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text="Business account's email address (used for login)", max_length=255, unique=True, verbose_name='email address')),
                ('role_position', models.CharField(blank=True, max_length=150, null=True, verbose_name='role/position')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='business name')),
                ('industry_category', models.CharField(blank=True, max_length=150, null=True, verbose_name='industry/category')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this business account should be treated as active.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the business account can log into admin site.', verbose_name='staff status')),
                ('is_email_verified', models.BooleanField(default=False, help_text="Designates whether business account's email has been verified", verbose_name='email verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when business account registered', verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, help_text="Date of business account's last login", null=True, verbose_name='last login')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time business account data was updated', verbose_name='updated at')),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'business account',
                'verbose_name_plural': 'business accounts',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='business_ac_email_e780c9_idx'), models.Index(fields=['is_active', 'is_email_verified'], name='business_ac_is_acti_e10365_idx')],
            },
        ),
    ]
