# Generated by Django 5.2.8 on 2026-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0002_businessaccount_is_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='business_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='business email'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='website'),
        ),
    ]
