# Generated by Django 5.2.8 on 2026-04-05 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0003_businessaccount_business_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Status of the verification request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_account', models.ForeignKey(help_text='The business account receiving the request', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='business_account.businessaccount')),
                ('user', models.ForeignKey(help_text='The user requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification request',
                'verbose_name_plural': 'verification requests',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'business_account')},
            },
        ),
    ]
