# Generated by Django 5.2.8 on 2026-04-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0004_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text="Business account's cover photo", null=True, upload_to='business_cover_photos/', verbose_name='cover photo'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='headline',
            field=models.CharField(blank=True, help_text='A short headline or status for the business profile', max_length=255, null=True, verbose_name='headline'),
        ),
    ]
