# Generated by Django 5.2.8 on 2026-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0005_businessaccount_cover_photo_businessaccount_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='about',
            field=models.TextField(blank=True, help_text="Business account's about section", null=True, verbose_name='about'),
        ),
    ]
