# Generated by Django 5.2.8 on 2026-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0006_businessaccount_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Business account's profile picture", null=True, upload_to='business_profile_pictures/', verbose_name='profile picture'),
        ),
    ]
