# Generated by Django 5.2.8 on 2026-05-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0007_businessaccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the business account has been verified by the admin', verbose_name='verified'),
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Verification document (PDF, Image, etc.)', upload_to='business_verification_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('hold', 'Hold')], default='pending', help_text='Status of the verification request', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from the admin', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_account', models.OneToOneField(help_text='The business account requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='verification_document', to='business_account.businessaccount')),
            ],
            options={
                'verbose_name': 'business verification',
                'verbose_name_plural': 'business verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
