# Generated by Django 5.2.8 on 2026-05-07 21:14

import business_account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0008_businessaccount_is_verified_businessverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='email',
            field=models.EmailField(db_index=True, help_text="Business account's email address (used for login)", max_length=255, unique=True, validators=[business_account.validators.validate_is_business_email], verbose_name='email address'),
        ),
    ]
