# Generated by Django 5.2.8 on 2026-05-07 21:46

import business_account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0009_alter_businessaccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessverification',
            name='document',
            field=models.FileField(help_text='Verification document (PDF, Image, etc.)', upload_to='business_verification_docs/', validators=[business_account.validators.validate_verification_document]),
        ),
    ]
