# Generated by Django 5.2.8 on 2026-05-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('chat_message', 'New Chat Message'), ('recommendation', 'New Recommendation'), ('verification_request', 'New Verification Request'), ('verification_update', 'Verification Status Update'), ('post_proposal', 'New Post Proposal'), ('new_follow', 'New Follower'), ('new_post', 'New Post Activity'), ('system_alert', 'System Alert')], max_length=50),
        ),
    ]
